version: '3.8'
services:
  web:
    build: .
    environment:
      - FLASK_APP=app.main:app
    command: flask run --host=0.0.0.0
    volumes:
      - ./app:/code/app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: home_automation
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data: